### ISSUE TITLE
Cannot delete a game 500 internal server error

### ISSUE THREAD

**Issue by RotaruDan** [e-ucm/rage-analytics-backend#87]
Frontend logs
```
TypeError: Cannot read property '_id' of undefined
    at app.js:962
    at angular.js:11486
    at processQueue (angular.js:16383)
    at angular.js:16399
    at Scope.$eval (angular.js:17682)
    at Scope.$digest (angular.js:17495)
    at Scope.$apply (angular.js:17790)
    at done (angular.js:11831)
    at completeRequest (angular.js:12033)
    at XMLHttpRequest.requestLoaded (angular.js:11966)

```

Backend logs:

```
back           | DELETE /api/games/589351d3357163006eec75c0 500 1.794 ms - -
back           | TypeError: versions.remove is not a function
back           |     at /app/lib/games.js:14:18
back           |     at /app/node_modules/easy-collections/node_modules/async/lib/async.js:731:23
back           |     at /app/node_modules/easy-collections/node_modules/async/lib/async.js:172:37
back           |     at /app/node_modules/easy-collections/node_modules/async/lib/async.js:689:13
back           |     at iterate (/app/node_modules/easy-collections/node_modules/async/lib/async.js:265:13)
back           |     at async.forEachOfSeries.async.eachOfSeries (/app/node_modules/easy-collections/node_modules/async/lib/async.js:284:9)
back           |     at _parallel (/app/node_modules/easy-collections/node_modules/async/lib/async.js:688:9)
back           |     at Object.async.series (/app/node_modules/easy-collections/node_modules/async/lib/async.js:710:9)
back           |     at Collection.executePreRemove (/app/node_modules/easy-collections/lib/collection.js:104:11)
back           |     at Collection.removeById (/app/node_modules/easy-collections/lib/collection.js:73:17)
back           |     at /app/lib/games.js:101:30
back           |     at _fulfilled (/app/node_modules/q/q.js:834:54)
back           |     at self.promiseDispatch.done (/app/node_modules/q/q.js:863:30)
back           |     at Promise.promise.promiseDispatch (/app/node_modules/q/q.js:796:13)
back           |     at /app/node_modules/q/q.js:604:44
back           |     at runSingle (/app/node_modules/q/q.js:137:13)

```

**Comment by RotaruDan** [comment]
Fixed by https://github.com/e-ucm/rage-analytics-backend/pull/88
